package commander.opcode;
public enum Opcode {
	// Client sends
	NEW_ROOM, JOIN_ROOM, EXIT_ROOM, EXIT_GAME, END_GAME,

	// Server sends
	ERROR, NEW_CLIENT, CLIENT_ACCEPTED, ROOM_CREATED, ROOM_TIMEOUT, JOIN_MEMBER, ROOM_ACCEPTED, LEAVE_MEMBER,
	START_GAME,

	// Both sends
	MOVE, SHOOT, SET_TRAP,
}
